#ifndef __CONFIG_H__
#define __CONFIG_H__

#define NAGI_PROMPT_STR CONFIG_IDF_TARGET
#define NAGI_MAX_COMMAND_LINE_LENGTH 1024

#define NAGI_WS2812_GPIO_NUM 8
#define NAGI_WS2812_LED_NUM 1

#define NAGI_AXIS_USE_ADC_CONTINUOUS 1
#define NAGI_MAX_NUM_OF_AXES 1
#define NAGI_AXIS_JITTER_THRESHOLD 8
#define NAGI_MAX_NUM_OF_BUTTONS 9
#define NAGI_BUTTON_JITTER_THRESHOLD 5
#define NAGI_MAX_NUM_OF_ENCODERS 2

#endif // __CONFIG_H__